### ISSUE TITLE
Config files are not considered

### ISSUE THREAD

**Issue by Kitton** [hexpm/diff#39]
The change was done in `config/config.exs`, but it's not displayed

Example: https://diff.hex.pm/diff/pagantis_elixir_tools/0.17.0..0.17.1
This change should be shown https://github.com/digitalorigin/pg-elixir-tools/commit/c4d126f22c19f2c7e3125d58938d805a8ff87adb

**Comment by wojtekmach** [comment]
Config files are not included by default in your package, thats why they don’t show up in diff, see: https://hexdocs.pm/hex/Mix.Tasks.Hex.Build.html#module-package-configuration.

**Comment by Kitton** [comment]
@wojtekmach but considering that on https://diff.hex.pm/ we can't pass anything to `:files` does it make sense to add `config` folder to the default values?

**Comment by wojtekmach** [comment]
Sorry, perhaps I wasn't clear. diff.hex.pm does not display config files for your project because these are not added to packages by default and you haven't overridden `:files` in your project to include them. If you would they would show up.

We are not planning to add config to packages because application env is discouraged for packages: https://hexdocs.pm/elixir/library-guidelines.html#avoid-application-configuration. Furthermore, the config files are really just for the developers of the package, it's not being loaded when end users use the package. (To set application env for users of the package, you need to set `:env` in `application/0` in your mix.exe file but, again, application env should be mostly avoid for libraries)
